language: c
branches:
  only:
  - draft
env:
  global:
  - default_branch_scenario: "published/subcountry2014"
  - study_area: "Belize"
  - secure: OrhOIjkbNgCqQeGtWJ54s3AIbnqTcG68TA5ivzD5PI4QiAKzA0UBAo9DkFlW5DX0K8uwuPhsX2eqMjOWtyFhHH+AFIfjipnkDCgMoII5kSOq4NZweLJsYGS9cgl2+bluJFtMOgU1lzVtQnWeHFSqBkFIY1T9J4buaNvIaSIBsjM=
matrix:
  fast_finish: true
before_install:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- curl -OL http://raw.github.com/OHI-Science/ohi-webapps/master/ohi-travis-functions.R
- chmod 755 ./travis-tool.sh
- ./travis-tool.sh bootstrap
- sudo apt-get install pandoc
install:
- ./travis-tool.sh install_r zoo
- ./travis-tool.sh install_r psych
- ./travis-tool.sh install_r tidyr
- ./travis-tool.sh install_r brew
- ./travis-tool.sh install_r rmarkdown
- ./travis-tool.sh install_r httr
- ./travis-tool.sh install_r git2r
- ./travis-tool.sh install_github ohi-science/rCharts
- ./travis-tool.sh install_github ohi-science/ohicore@dev
- git config --global user.email "lowndes@nceas.ucsb.edu"
- git config --global user.name "Julia Lowndes"
script:
- Rscript ohi-travis-functions.R calculate_scores && Rscript ohi-travis-functions.R
  create_results && Rscript ohi-travis-functions.R push_branch draft && Rscript ohi-travis-functions.R
  push_branch published && Rscript ohi-travis-functions.R create_pages
after_failure:
- ./travis-tool.sh dump_logs
notifications:
  email:
    recipients:
    - bbest@nceas.ucsb.edu
    - lowndes@nceas.ucsb.edu
    on_success: change
    on_failure: always
